In [15]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [1]:
import pandas as pd

In [4]:
df=pd.read_csv('student_performance.csv')

In [6]:
df.head(5)

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [7]:
df.shape

(30, 13)

In [22]:
print(df.iloc[4].shape)

(13,)

In [16]:
df.dtypes

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [21]:
df.columns.tolist()

['student_id',
 'name',
 'age',
 'gender',
 'department',
 'semester',
 'math_score',
 'science_score',
 'english_score',
 'programming_score',
 'attendance_percentage',
 'city',
 'admission_year']

In [23]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [25]:
df.isna().sum()

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [30]:
import numpy as np
df.loc[df.index[:5], 'math_score']= np.nan

In [33]:
df['math_score'].isnull().sum()

np.int64(5)

In [34]:
df.isna().sum()

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               5
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [45]:
print((df['gender']=='Male').sum())
print((df['gender']=='Female').sum())
print((df['city'].nunique()))
df['city'].value_counts()

15
15
25

city
Kochi                 2
Lucknow               2
Thiruvananthapuram    2
Agra                  2
Kolkata               2
Hyderabad             1
Mumbai                1
Delhi                 1
Ahmedabad             1
Varanasi              1
Bangalore             1
Pune                  1
Jaipur                1
Mysore                1
Thrissur              1
Bhopal                1
Chennai               1
Patna                 1
Nagpur                1
Dehradun              1
Chandigarh            1
Surat                 1
Allahabad             1
Kanpur                1
Indore                1
Name: count, dtype: int64

In [51]:
cs_students = df[df['department'] == 'Computer Science']

In [57]:
cs = pd.DataFrame(
    cs_students[
        (cs_students['city'] == 'Chennai') |
        (cs_students['city'] == 'Mumbai')
    ]
)

In [58]:
cs['programming_score']

0    91
Name: programming_score, dtype: int64

In [67]:
df[df['attendance_percentage']<=75]

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
5,1006,Meera Joshi,20,Female,Electronics,2,58.0,66,70,52,72,Pune,2023
8,1009,Rahul Mishra,20,Male,Mechanical,2,62.0,71,58,45,68,Varanasi,2023
14,1015,Ajay Tiwari,19,Male,Computer Science,2,71.0,69,64,76,75,Bhopal,2023
16,1017,Manoj Pandey,21,Male,Civil,2,56.0,61,55,38,65,Patna,2023
20,1021,Harish Pillai,20,Male,Electronics,2,64.0,70,67,58,74,Thiruvananthapuram,2023
22,1023,Sanjay Dubey,21,Male,Civil,2,61.0,66,59,42,70,Allahabad,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60.0,65,68,39,73,Thiruvananthapuram,2023

In [72]:
df['math_score'].idxmin()

16

In [77]:
df['total_score'] = df['math_score'] + df['science_score'] + df['english_score'] + df['programming_score']
print(df['total_score'].idxmin())
print(df['total_score'].idxmax())

16
9