In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
#Labelencode :converts text categories to integers (Male-0,fenale-=1)
#Standardscaler :scales numbers so all features have smae range
#DecisionTreeRegressor builds a trees  if/else rules to predict

In [ ]:
df=pd.read_csv('student_performance.csv')

In [ ]:
df.head(10)

   student_id          name  ...       city admission_year
0        1001  Aarav Sharma  ...     Mumbai           2023
1        1002   Priya Patel  ...  Ahmedabad           2023
2        1003   Rohit Verma  ...      Delhi           2023
3        1004   Sneha Reddy  ...  Hyderabad           2023
4        1005    Arjun Nair  ...      Kochi           2023
5        1006   Meera Joshi  ...       Pune           2023
6        1007   Kiran Kumar  ...  Bangalore           2023
7        1008   Divya Singh  ...    Lucknow           2023
8        1009  Rahul Mishra  ...   Varanasi           2023
9        1010    Ananya Das  ...    Kolkata           2023

[10 rows x 13 columns]

In [ ]:
df.isna().sum()
print(df.isna().sum().sum())

0

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.describe()

        student_id        age  ...  attendance_percentage  admission_year
count    30.000000  30.000000  ...              30.000000            30.0
mean   1015.500000  19.733333  ...              84.500000          2023.0
std       8.803408   0.739680  ...               9.379913             0.0
min    1001.000000  19.000000  ...              65.000000          2023.0
25%    1008.250000  19.000000  ...              77.250000          2023.0
50%    1015.500000  20.000000  ...              86.500000          2023.0
75%    1022.750000  20.000000  ...              91.750000          2023.0
max    1030.000000  21.000000  ...              98.000000          2023.0

[8 rows x 9 columns]

In [ ]:
df_ml=df.copy()
le_gender=LabelEncoder()
df_ml['gender_encoded']=le_gender.fit_transform(df_ml['gender'])

print(f"Gender eoncoding: {dict(zip(le_gender.classes_,le_gender.transform(le_gender.classes_)))}\n")

le_dept=LabelEncoder()
df_ml['department_encoded']=le_dept.fit_transform(df_ml['department'])

print(f"\nDepartment eoncoding: {dict(zip(le_dept.classes_,le_dept.transform(le_dept.classes_)))}\n")



print("\n New Columns added:\n")
df_ml[['gender','gender_encoded','department','department_encoded']].head(10)

Gender eoncoding: {'Female': np.int64(0), 'Male': np.int64(1)}


Department eoncoding: {'Civil': np.int64(0), 'Computer Science': np.int64(1), 'Electronics': np.int64(2), 'Mechanical': np.int64(3)}


 New Columns added:

   gender  gender_encoded        department  department_encoded
0    Male               1  Computer Science                   1
1  Female               0  Computer Science                   1
2    Male               1       Electronics                   2
3  Female               0        Mechanical                   3
4    Male               1  Computer Science                   1
5  Female               0       Electronics                   2
6    Male               1             Civil                   0
7  Female               0  Computer Science                   1
8    Male               1        Mechanical                   3
9  Female               0  Computer Science                   1

In [ ]:
#Select features and define tarhet
features_cols=[
    'math_score','science_score','english_score','attendance_percentage','gender_encoded','department_encoded'
]

X=df_ml[features_cols]
Y=df_ml['programming_score']

print(f"Feature matrix X shape:{X.shape}")
print(f"Target vector Y shape :{Y.shape}")
print(f"Features columns:{features_cols}")
print(f"Target Columns :programmingscore")
print(f"Target range: {Y.min()} to {Y.max()} (mean :{Y.mean():.1f})")

Feature matrix X shape:(30, 6)
Target vector Y shape :(30,)
Features columns:['math_score', 'science_score', 'english_score', 'attendance_percentage', 'gender_encoded', 'department_encoded']
Target Columns :programmingscore
Target range: 38 to 97 (mean :67.6)